### ISSUE TITLE
gambling..

### ISSUE THREAD

**Issue by strepera** [snailifyxd/snail-bridge#2]
1. give members coins for chatting and winning games
2. you can make a bet for 2 other people and decide who wins and what the wager is if both of them agree
3. you can coinflip someone else
4. you can roll a dice and guess the number alone or with someone else
5. you can buy chat separators with coins and theres a coin leaderboard
6. you can use parties to spam the gambling commands
7. you get messaged to accept gambling duels
8. replace gexp requirement with buying guild ranks??

**Comment by fuzionqt** [comment]
### Introducing "SnakeCoins":
> Curated by Snailify in collaboration with FUZION for the Nope Ropes community.

- [x] **Earn Coins:** Receive approximately 15 coins per chat message, with significant bonuses for winning games.
  - @snailifyxd in collaboration with @fuzionqt 

- [ ] **Guild Challenges:** Challenge Guild Mates to a 50/50 coin flip for X amount of SnakeCoins.
  - @fuzionqt 

- [x] **Bot Coin Flips:** Engage in coin flips against a Bot, similar to PvP challenges.
  - @fuzionqt 

- [x] **Dice Rolls:** Roll two dice (1 to 12), rigged akin to "High Archfiend Dice" - odds against you, but with potential for substantial wins.
  - @snailifyxd 

- [x] **SnakeShop:** Visit the "SnakeShop" to spend earned SnakeCoins on prefixes and chat vanities.
  - @snailifyxd - [View prefix.js](https://github.com/snailifyxd/snail-bridge/blob/89ad035197a64b0cbfa7c91c402165a07418c812/client/commands/prefix.js)

- [x] **Guild Leaderboard:** Establish a Guild Leaderboard for players to compete for the top spot.
  - @snailifyxd

- [x] **Guild Parties:** Implement a guild party feature where the bot invites players to join games together.
  - @snailifyxd

- [ ] **Participation DMs** Bot will message players and contestants before launching a game for confirmation.
  - @snailifyxd 

- [ ] **Purchase Guild Ranks** Replace the old Guild Experience system and replace it with a system where you can purchase ranks.
  - @snailifyxd
